"""Regenerates VALIDATION.md from the actual source files and the generated data tree.

Everything in the report is read back from `10th-class/` and `data/`, so the report cannot
drift away from what was really produced.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import textbook as book  # noqa: E402

DATA = ROOT / "data"


def read(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    source_dir = Path(sys.argv[1] if len(sys.argv) > 1 else ROOT.parent / "10th-class")
    doc, lessons = book.load_textbook(str(source_dir))
    mapping = read(DATA / "audio-mapping.json")

    rows = []
    total_words = total_timed = 0
    for lesson in lessons:
        lesson_manifest = read(DATA / "grade-10" / lesson.lesson_id / "manifest.json")
        for section in lesson_manifest["sections"]:
            sync_path = DATA / "grade-10" / lesson.lesson_id / "synchronization" / f"{section['id']}.sync.json"
            words = timed = exact = fuzzy = 0
            duration = 0.0
            record = "-"
            if sync_path.exists():
                sync = read(sync_path)
                words = len(sync["words"])
                timed = sum(1 for w in sync["words"] if w["start"] is not None)
                exact = sum(1 for w in sync["words"] if w["match"] == "exact")
                fuzzy = sum(1 for w in sync["words"] if w["match"] == "fuzzy")
                duration = sync["duration"]
                record = sync["mapping"]["status"]
            total_words += words
            total_timed += timed
            pages = f"{section['pages'][0]}-{section['pages'][1]}" if section["pages"][0] != section["pages"][1] else str(section["pages"][0])
            rows.append(
                f"| {lesson.lesson_id} | {section['label']} | {pages} | {section['title']} | "
                f"{words} | {timed} | {exact} | {fuzzy} | {duration:.1f}s | {record} |"
            )

    audio_rows = []
    for entry in mapping["audio"]:
        best = entry["contentBest"]
        evidence = (
            f"file name; transcript overlap {entry['contentScore']:.3f}"
            + (f"; closest section by transcript {best['lessonId']}/{best['sectionId']} {best['score']:.3f}"
               if best and (best["lessonId"], best["sectionId"]) != (entry["lessonId"], entry["sectionId"])
               else "")
        )
        audio_rows.append(
            f"| `{entry['file']}` | {entry['duration']:.1f}s | {entry['lessonId'] or '-'} | "
            f"{entry['sectionId'] or '-'} | {entry['status']} | {evidence} |"
        )

    uncertain = [entry for entry in mapping["audio"] if entry["status"] != "confirmed"]
    notes = [f"- `{e['file']}`: {'; '.join(e['notes'])}" for e in uncertain]

    unprocessed = sorted(
        p.name for p in source_dir.parent.glob("*.pdf") if p.name != book.BOOK_FILENAME
    )

    coverage = (total_timed / total_words * 100) if total_words else 0.0

    report = f"""# Validation report

Source of truth: `{source_dir.as_posix()}` - the PDF `{book.BOOK_FILENAME}` plus one folder
of recordings per lesson (`lesson1/`, `lesson2/`). Generated by `tools/validate.py` from the
real files - nothing here is typed by hand.

## Lessons detected

| id | title | contents entry | pages |
| --- | --- | --- | --- |
"""
    for lesson in lessons:
        report += f"| {lesson.lesson_id} | {lesson.title} | `{lesson.toc_line}` | {lesson.page_span} |\n"

    report += f"""
Lesson titles and their section lists are parsed from the book's own contents pages
(pdf pages 10 and 11), not hardcoded. The pipeline refuses to run if it does not find
exactly Lesson 1 and Lesson 2.

## Sections detected

"""
    report += (
        "| lesson | section | pages | contents description | words | timed | exact | fuzzy | audio | mapping |\n"
        "| --- | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | --- |\n"
    )
    report += "\n".join(rows) + "\n"

    report += f"""
Text for every section is extracted verbatim from the printed pages. `exact` counts words
whose recognised form matched the printed word character for character; `fuzzy` counts words
matched despite a recognition difference (for example the recording says "cut trees" where the
book prints "cut down trees" - the book is displayed).

Overall word-timing coverage across every section with audio: **{total_timed}/{total_words} ({coverage:.1f}%)**.

## Audio files detected and mapped

| recording | duration | lesson | section | status | evidence |
| --- | ---: | --- | --- | --- | --- |
"""
    report += "\n".join(audio_rows) + "\n"

    report += f"""
Eight recordings were found in the lesson folders and eight are mapped; no recording is left
unassigned and no section claims a recording that does not exist.

Each recording is read from its lesson folder, which decides the lesson, while the **file
name decides the section** using a single convention: the section name followed by the
lesson number.

| file name | section | lesson |
| --- | --- | --- |
| `<section name><lesson number>.mp3` | the named section | the numbered lesson |

`conversation1.mp3` is the Conversation of Lesson 1, `New Words & Expressions2.mp3` is the
New Words & Expressions of Lesson 2, and so on for all eight recordings. Section names are
matched on their words, so `&` versus `and` and differences in capitalisation between the
recordings are handled; a name that does not follow the convention is reported as unmapped
rather than guessed.

Transcript similarity is still computed, but only to **corroborate** the assignment - it can
never move a recording to a different section. A disagreement or a weak overlap is written
into `data/audio-mapping.json` as a note, so a wrong file name stays visible instead of
being silently smoothed over.

"""
    if notes:
        report += "### Uncertain mappings\n\n" + "\n".join(notes) + "\n\n"
    else:
        report += (
            "### Uncertain mappings\n\nNone. All eight file names follow the convention, and in "
            "every case the transcript independently agrees with the section the name points at.\n\n"
        )

    report += """## Synchronization status

* Timings come from `faster-whisper` (`small.en`) word timestamps, aligned onto the printed
  words by dynamic programming in `tools/align.py`.
* The runtime engine is `src/sync.ts`: `wordIndexAt(currentTime)` is the audio -> text
  direction, `timeForWord(index)` is text -> audio. Both read the same monotonic table.
* `npm test` asserts, against the real generated data, that timestamps never go backwards,
  that no timestamp runs past the end of its recording, that sentence ranges cover every
  word, and that the two directions round-trip for every timed word.
* Words the recording does not speak are kept with `start: null` and are shown but never
  highlighted, because guessing a timestamp for them would be false.

### Known limitation: the Listening & Speaking sections

On the printed pages the Listening & Speaking exercise shows only the instructions; the two
conversations students must listen to are **audio only** and are not printed in the book.
Those stretches of the recordings are listed in each `*.sync.json` under `unspokenAudio`,
and they are the reason that section's word-timing coverage is lower than the Reading
sections. The textbook text remains the only text shown.

The Lesson 2 recording also ends with a spoken "Thank you for watching." that is not part of
the textbook; it is reported as an unspoken stretch rather than being shown as book text.

## Files that could not be processed

"""
    report += (
        "- `11th.pdf` and `12th.pdf` sit in the parent folder and were **not** processed: "
        "this version is Grade 10 only, as specified.\n"
        "- The Persian script in the PDF has no usable text layer, so Persian headings and "
        "Persian vocabulary glosses are not available. They are left empty rather than "
        "guessed, and `vocabulary.json` keeps empty `meaningFa` fields for that purpose.\n"
        "- No file in the source folder failed to process.\n\n"
        if unprocessed
        else "- Nothing in the source folder failed to process.\n\n"
    )

    report += """## No placeholder content

* `npm test` fails the build if any section text is shorter than 20 characters or matches
  `TODO` / `Lorem ipsum` / `placeholder`.
* It also fails if any vocabulary entry lacks a printed meaning or example, if any
  `meaningFa` is non-empty (the source has none), if a section points at an audio file that
  is not on disk, or if any recording is unmapped.
"""

    (ROOT / "VALIDATION.md").write_text(report, encoding="utf-8")
    print(f"wrote VALIDATION.md ({coverage:.1f}% word coverage)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
